### ISSUE TITLE
Copying of logs not working anymore after infra update

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/usage_plots#22]
https://abibuilder.cs.uni-tuebingen.de/jenkins/job/usage_statistics/job/usageStatistics/134/console

I actually thought this was fixed long ago.

**Comment by jpfeuffer** [comment]
The Files on abi-services are not readable!

**Comment by jpfeuffer** [comment]
After fixing, please test the full job since I needed to update the docker container.

**Comment by timosachsenberg** [comment]
strange... pretty sure that this worked at some point, but I can confirm:
(base) builder@abibuilder3:~$ scp 'buildusr@abi-services:/var/log/apache2/seqan-update_access.log*' ./tmp
scp: /var/log/apache2/seqan-update_access.log: Permission denied

**Comment by timosachsenberg** [comment]
are again available on our jenkins
